### PR TITLE
Fix unhandled promise rejection on server.open

### LINKED ISSUE #1231: UnhandledPromiseRejectionWarning when serving fresh installation
I am using Pattern Lab Node `v14.7.0` on `Linux`, with Node `v14.7.0`, using a `Vanilla` Edition.

##### Expected Behavior
It should build everything and run the server without generating errors or warnings.

##### Actual Behavior
```
Pattern Lab is being served from http://127.0.0.1:3000
(node:201) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/root/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:421:26)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Socket.<anonymous> (internal/child_process.js:442:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:673:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The server does run and it looks like everything works as expected, but the deprecation warning makes me nervous. I don't want to be unable to upgrade node later without breaking Pattern Lab.

##### Steps to Reproduce

1. docker container run -ti --rm node:14.7.0 /bin/bash
1. cd
1. npm create pattern-lab
    1. ./
    1. Handlebars
    1. Handlebars base patterns (some basic patterns to get started with)
    1. Y
1. npm run pl:build
1. npm run pl:serve

### PR DESCRIPTION
**Pull request by JosefBredereck**
Closes #1231 

Summary of changes:

In a docker container with no browser installed, an unhandled promise rejection occured when `pl:serve` tried to open pattern lab in a browser.

### CODE REVIEW

**Review by sghoweri — APPROVED** [review]
👍

**Comment by fgm** [comment]
Any reason npm create still uses 5.12.0 ? NPMJS doesn't carry create-pattern-lab 5.13.0 yet. Also, when manually installing @pattern-lab/cli 5.13.0 in an empty directory (macOS Mojave):

- doing `npx pattern-lab init` crashes with `env: node\r: No such file or directory`. Apparently caused by the file being in Windows CRLF format instead of *nix LF format
- doing `node node_modules/.bin/pattern-lab init` to avoid the CRLF issue still emits this deprecation warning about unhandled promise rejection:
```
$ patternlab install --config ./patternlab-config.json
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at makeError (/Users/fgm/src/OSInet/fr/osinet/osinet9/static/plab/node_modules/execa/index.js:172:9)
    at /Users/fgm/src/OSInet/fr/osinet/osinet9/static/plab/node_modules/execa/index.js:277:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:15124) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15124) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠏ ⊙ patternlab → Installing starterkit @pattern-lab/starterkit-twig-demo
````
It then remains (indefinitely ?) on that last line, with the node process no longer eating any CPU, so apparently stuck.

**Comment by JosefBredereck** [comment]
Oh, yes. I had no access rights to the npm package but I should now have. I will change that today. Very good hint.

**Comment by JosefBredereck** [comment]
Also, your error message looks more like #916, where an error occurs during installation.

**Pull request merged**
