### PR TITLE
BREAKING-CHANGE: Deprecate underscore prefix

### LINKED ISSUE #1182: Deprecate Pattern Hiding Using `_` before the file name
Converted from https://github.com/orgs/pattern-lab/projects/3

http://patternlab.io/docs/pattern-hiding.html

**BM: Use markdown instead. Filesystem hacks suck**

### LINKED ISSUE #1183: Deprecate Hiding Folders of Patterns Using _ before the directory name
Converted from https://github.com/orgs/pattern-lab/projects/3

https://github.com/pattern-lab/the-spec/issues/27

**BM: I know this passed, but I really don't like filesystem-based solutions like this**

### LINKED ISSUE #1209: Implement hidden key in frontmatter
I've been reconciling https://patternlab.io/docs/documenting-patterns/ with #1208 - I realized that we have support for parsing all these keys, yet core may not do something yet with all of them:

* `excludeFromStyleguide`
* **`hidden`**
* `links`
* `order`
* `state`
* `tags`
* `title`

This issue is limited to adding `hidden` functionality to https://github.com/pattern-lab/patternlab-node/blob/dev/packages/core/src/lib/ui_builder.js#L83-L90

### PR DESCRIPTION
**Pull request by JosefBredereck**
Closes #1209 
Closes #1182 
Closes #1183 

Summary of changes:

Change the way pattern lab is hiding patterns. Because all those file system hacks are not a good approach we decided to remove this functionality in favor of a more flexible way.

### CODE REVIEW

**Comment by JosefBredereck** [comment]
@bmuenzenmeyer @sghoweri @engelfrost @bradfrost @mfranzke @ringods 
Is it more convenient to have the companion file for `pattern-groups` in the folder or next to the folder?
The same question appears for `patter-sub-groups`.

To overcome the pattern and group name matching I consider an underscore prefix for version 1 if it is a companion `.md` file of the group. 

Examples (Sorted like the filesystem would do)
1. Inside the folder
```
_patterns/atoms/text/
_patterns/atoms/text/_text.md
_patterns/atoms/animation/
_patterns/atoms/animation/_animation.md
_patterns/atoms/_atoms.md
_patterns/molecules/blocks/
_patterns/molecules/blocks/_blocks.md
_patterns/molecules/cards/
_patterns/molecules/cards/_cards.md
_patterns/molecules/_molecules.md
```
2. Next to the folder

```
_patterns/atoms/text/
_patterns/atoms/animation/
_patterns/atoms/animation.md
_patterns/atoms/text.md
_patterns/molecules/blocks/
_patterns/molecules/cards/
_patterns/molecules/blocks.md
_patterns/molecules/cards.md
_patterns/atoms.md
_patterns/molecules.md
```

### **!! please upvote with 🚀 if you like version 1 and with 👀  if you prefer version 2 !!**

**EDIT**: I know we have the top-level markdown files (as documentation patterns), which apply to version 2 in this example. The problem is, those are breaking the UI even without any change in the current version that no view all pages can be generated for folders with documentation blocks. Maybe we need to rethink how everything is working together.

**EDIT 2**: Based on all the information I got from issues and also the spec, I can now confirm, that version 2 was somehow implemented but, on the other hand, not.  References: #415, [the-spec/#28](https://github.com/pattern-lab/the-spec/issues/28) and also an old [PR](https://github.com/pattern-lab/patternlab-php-core/pull/141) where I gathered some more information. I will now proceed to use version 2 since it is already implemented in some way.

**Comment by JosefBredereck** [comment]
just answered the question by myself as I wanted to update the starter kit demos.
If you have a pattern with the same as the subgroup you cant manage to order/hide the subgroup anymore and also the pattern data would apply to the subgroup.
Example: `_patterns/atoms/buttons/buttons.twig`
Will require `_patterns/atoms/buttons/buttons.md` for the pattern and also the subgroup. 😕

**Comment by coreylafferty** [comment]
If I understand this correctly, I'm on team 🚀.  Generally I think all the files for a subfolder should be in that folder so it's self-contained.  In our theme we have a script that automatically generates a subfolder containing the necessary files (e.g., twig, md, scss and yml files).

**Comment by JosefBredereck** [comment]
Keep in mind, this change is not for patterns. It is for groups and subgroups. But I'm totaly on you side. We also have scripts to create all required files in our company.

**Comment by JosefBredereck** [comment]
See my edits on my initial question, "commented on 18 Aug.". There are some hints for testing.

**Pull request merged**
