### PR TITLE
chore(repo): retires Brian from active involvement

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**
I need to step away from PL. I am very happy to see it in good hands and active.

This PR removes active references to me, but retains some of the licensing and author fields. If that needs to be normalized, do so.

I've deactivated my patreon account. It was the main source of funding for the open source netlify team we pay for each month.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@sghoweri you have access to netlify, would you be able to update the payment settings?

**Comment by JosefBredereck** [comment]
That's sad to hear. I wish you all the best for the future and thank you very much for traveling with us to this point 🚀

**Comment by ringods** [comment]
@bmuenzenmeyer sad to see you go. But all the best for the future!

**Comment by mfranzke** [comment]
@bmuenzenmeyer it was an honour and a pleasure ! Very sad to hear. But all the best !!!

**Comment by sghoweri** [comment]
Really sad to see you go @bmuenzenmeyer but like all things in life, I also know that nothing lasts forever. 😢

From the bottom of my heart, thank you so so very much for all the time, care, and energy put into making Pattern Lab and the Pattern Lab community the very best it can be all these years. Seriously gonna miss working with ya Brian so please don't be a stranger ❤️.

I just switched all the Netlify billing over to me (*gulp*) and removed you from the Netlify account Brian. 

We'll have to figure out a better longer term strategy for managing that (CC @mfranzke @ringods @JosefBredereck) but I'll foot the bill (ie. overages, extra fees on top of our OSS account with Netlify) till we cross that bridge.

**Review by sghoweri — APPROVED** [review]
So if I don't approve this, that means you can't leave, right @bmuenzenmeyer? 😅

**Comment by ringods** [comment]
I'm usually eager to merge branches as a means to make progress. But I can't call these changes "progress", although Brian, you are progressing your life. 🤝

**Pull request merged**
