### PR TITLE
Refactor the root Pattern Lab build into a proper class

### PR DESCRIPTION
**Pull request by geoffp**
Addresses #572 

Summary of changes:
I've begun the process of refactoring the loosely organized build step into a real class with a real constructor. The goal here is to make to whole process more comprehensible ahead of the async work, which would be difficult to reason about and debug without it.

I plan to continue this work in small, careful steps.

If you merge, please leave the branch and I'll just keep jamming on it as time allows. Async rendering or bust.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
pardon the commit to this - all the 💯 goes to @geoffp on this!

**Comment by bradfrost** [comment]
I'm way out of my depths here, but it looks like fascinating and nitty-gritty work. Thanks @geoffp!

**Comment by geoffp** [comment]
Thanks fellas! It is pretty abstract work, but damn if I don’t enjoy a good refactoring.

**Comment by bradfrost** [comment]
@geoffp ha! You sound like me refactoring the frontend code. I'm one of those weirdos that likes spring cleaning and organization and stuff. ¯\_(ツ)_/¯

**Comment by geoffp** [comment]
@bradfrost hey, I know the feeling. It’s nice to take up something kinda messy and leave behind something beautiful, whether it’s visual or in code.

**Pull request merged**
