### PR TITLE
better regex for replacing single quotes

### PR DESCRIPTION
**Pull request by e2tha-e**
Addresses #250 (preliminary work)

Summary of changes:
@bmuenzenmeyer Tightening up the regex for JSON parsing parameter submission. Needed better regex for single-quote wrapped keys. Also, don't need the m flag.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Before this gets merged I'd really like to see parameter_hunter unit tests written to cover the new supported syntaxes, if any.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer To accommodate the fact the you'd have to run through a matrix of parameter options, I refactored parameter_hunter_test.js to use less repetition of the currentPattern and patternlab objects. Now, the differences between tests are more obvious, and the file overall, is more readable. Unit tests are all passing. Please review.

**Comment by bmuenzenmeyer** [comment]
thanks for the cleanup and the addition tests @e2tha-e

**Comment by e2tha-e** [comment]
@bmuenzenmeyer On my commute to work, I realized I needed to account for more cases, so I'll be revisiting this shortly.

**Pull request merged**
