### PR TITLE
Regex and partial finding update on pattern-engines branch

### PR DESCRIPTION
**Pull request by e2tha-e**

### CODE REVIEW

**Comment by e2tha-e** [comment]
@bmuenzenmeyer @geoffp Please review

**Comment by bmuenzenmeyer** [comment]
@e2tha-e thanks for pivoting here - I appreciate the contribution and want it to see the light of day, and think this is the best route. pattern_engines are @geoffp's baby so I will let him rule in

**Comment by geoffp** [comment]
This looks good! The structure is well thought out. My only reservation is that breaking up the regexes makes it harder to paste them into a regex tester, but honestly, it's such a nightmare to edit them when they get that long that I think it's a good trade-off.

**Comment by geoffp** [comment]
@e2tha-e, if it breaks someday, now you have to fix. it. ;) Thanks for the good work!

**Comment by e2tha-e** [comment]
@geoffp Haha. Right on. Already on it!

**Pull request merged**
