### PR TITLE
Multiple pattern folders

### PR DESCRIPTION
**Pull request by bramsmulders**
Addresses #248 

Summary of changes:
A colleague of mine has altered patternlab to work with multiple pattern source folders. 
That was a good 4 months ago and i decided to pick up his work further. 
I've merged latest master into this branch and resolved some merge conflicts. 
All tests are running fine, and patternlab builds from multiple folders, whoop!

### CODE REVIEW

**Comment by bramsmulders** [comment]
All check are updated and pass now, so if you want this feature in PL-node you can merge it 😊

**Comment by bramsmulders** [comment]
Also keep in mind we need to update the watchers in the editions to match te multiple include folders

**Comment by bmuenzenmeyer** [comment]
After talking with Bram, I am repointing this PR to `dev-3.0`

**Comment by bramsmulders** [comment]
Any news on this PR @bmuenzenmeyer?

**Comment by bmuenzenmeyer** [comment]
Hi @bramsmulders thanks for the poke.
I plan to address this during my next open source day, 5/12

**Comment by bmuenzenmeyer** [comment]
reviewing this now

**Comment by bmuenzenmeyer** [comment]
this isnt working with the current gulp edition watches, failing within `normalizePath` when an array is passed in instead of a string. this must be fixed for both gulp and grunt editions prior to acceptance. I will get to this someday if it doesn't get coordinated before.

**Comment by bmuenzenmeyer** [comment]
I just received a :+1: for this idea from the awesome team at Altinn.

**Comment by bmuenzenmeyer** [comment]
i'd like to get this into 3.0 if we can. it needs some updating and edition love

**Comment by bramsmulders** [comment]
Hi @bmuenzenmeyer i thought it was already pointed to dev-3.0 branch right?

**Comment by bmuenzenmeyer** [comment]
Yes it is.  I just added the milestone to make it official

**Comment by mrosvik** [comment]
Will this change be a part of the next Pattern Lab release?  @bmuenzenmeyer

**Comment by bmuenzenmeyer** [comment]
@mrosvik It was intended for some time in the 3.0 space, yes. Funny thing is I do not recall closing this yesterday and I can no longer reopen the PR either. Github reports "The repository that submitted this pull request has been deleted."  

I will have to see if I have it local.

**Comment by bramsmulders** [comment]
That is weird! I indeed removed my fork, but i recall that PR's are stored in the "upstream" repository. See https://speakerdeck.com/holman/more-git-and-github-secrets?slide=114

Mayb if you close a PR it is no longer stored here? But you can see the changed files in the changed files tab. So that is weird

**Comment by askibinski** [comment]
@bmuenzenmeyer 
Looking at the latest 3.0 dev, this seems to got lost somewhere?

**Pull request closed without merging**
