### PR TITLE
Addresses #375 allow foo.json 

### PR DESCRIPTION
**Pull request by stevemartin**
Addresses #375

Summary of changes:

* glob data files in data folder, excluding listitems
* merge data as global data
* tests inform code style

### CODE REVIEW

**Comment by geoffp** [comment]
The code looks good to me!

**Comment by bmuenzenmeyer** [comment]
I am crazy excited to see another thorough, well-thought out PR @stevemartin - you don't know how much it means to me and @geoffp to receive contributions! :blush: 

My only comment would again be dependencies. We have lodash and a [custom merge function](https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/utilities.js#L29) which I think should do the same thing as the merge library you included. Can  you try either of those?

Again, this isn't meant to in any way degrade what you've done here. Merely trying to be mindful of dependencies/code bloat/redundancy as the project grows.  THANK YOU!

**Comment by stevemartin** [comment]
@bmuenzenmeyer no problem, all good learnings! :)

**Comment by bmuenzenmeyer** [comment]
will try to review this tomorrow!

**Pull request merged**
