### PR TITLE
fix(1049): Treat folders like patterns only if they're subfolders of …

### LINKED ISSUE #1049: Menu & View All list breaks if pattern name and folder name are identical
I am using Pattern Lab Node `v3.0.3` on `Windows`, with Node `v10.15.1`, using the `Twig` Edition.

##### Expected Behavior
All patterns show on the View All page and are properly nested in their parent item in the navigation.

##### Actual Behavior
If a filename matches that of the parent folder, the resulting menu shows the item outside the parent folder.  The same pattern does NOT show up on the View All page.

##### Steps to Reproduce

1. Start up a fresh copy of Pattern Lab Node, using the Twig engine and Twig starter kit.
2. Look at the Atoms / Buttons pattern in the menu and file system as an example. 
3. Notice that the Buttons item does not show in a Buttons folder (despite the file being 00-atoms/06-buttons/00-buttons.twig) and that Buttons does not show in either the main View All list or the Atoms category View All list.  

 
image

 
4.  As a clearer test, create the following four files to see how the menu handles similar patterns when the parent folder does and does not match one of them:

**Folder name (cats) does NOT match a pattern filename in it since it is plural**
/_patterns/01-molecules/cats/cat.twig
/_patterns/01-molecules/cats/cat-special.twig

**Folder name (dog) does match a pattern filename in it**
/_patterns/01-molecules/dog/dog.twig
/_patterns/01-molecules/dog/dog-special.twig

image

The two 'cat' files behave as expected, properly nested in a 'Cats' folder.  The dog items do not, with the 'dog' folder being created without a toggle to open it and 'dog special' not showing at all -- the other pattern shows outside the dog folder but does not show in the View All list (similar to the buttons example above).

### PR DESCRIPTION
**Pull request by kmonahan**
…pattern groupings

Closes #1049 

Summary of changes:
Limits the separated pattern-folder support to patterns that are nested at least two levels deep. This seems to be how the PHP version works and supports both of the following use cases:
`[patternType]/[patternSubType]/[pattern]/[pattern].hbs` (which appears to be the original intent of #992 and `[patternType]/[patternSubType]/[pattern].hbs`, where the pattern and patternSubType are the same (as in the use case in #1049, where the patternSubType `button` might contain `button.hbs` and `button--variant.hbs`.

### CODE REVIEW

**Comment by kryp71c** [comment]
It seems the pattern states are missing from the nav with this change.

**Comment by kmonahan** [comment]
Hey @kryp71c,
I'm not quite sure what you mean. Can you give an example of a pattern that's missing? I can then take a look.

**Comment by coreylafferty** [comment]
@kmonahan I think he means the state is missing.  For example, if you create a file named dog.md next to your dog.mustache or dog.twig file, and add the following contents:
```
---
el: .dog
title: Dog
state: inreview
---
```
the 'inreview' yellow dot doesn't show.  I suspect that's due to the removal of the 'info' variable being passed in.

**Comment by kmonahan** [comment]
Ah, got it. Thanks! WIll investigate and update my branch.

**Comment by kmonahan** [comment]
Dug into this one and I think what actually needs to be fixed here is what's being done in PR #1058 .

I tested locally with a pattern called Dog with a state of 'inreview' and a pattern called Dog Special with a state of 'inprogress'. When I organized the patterns in the `patternType/patternSubtype` structure (so my templates and markdown files were in `00-animals/dog/`), I see the state indicators in the nav:
animals-dog-dog

Likewise, when I organized the patterns in the `patternType/patternSubtype/pattern` structure (so the dog template and markdown files were in `00-animals/dogs/dog/`), I also see the state indicators in the nav:
animals-dogs-dog

Where I _don't_ see the indicators is when I use the `patternType/patternSubtype` structure with only one pattern in it: `00-animals/dog/` without the Dog Special pattern. Previously, this worked if the directory had the same name as the pattern but did not work if the names were different. When I rename my folder to "doggie", it's clearer that what's showing up in the nav is just the directory with no subnav listing the patterns underneath it, and hence no status indicator:
Screen Shot 2019-09-18 at 2 18 56 PM

Rather than have the status indicator appear in the nav next to the pattern subtype name if it matches the pattern, my desired behavior here would be for the pattern subtype to have a submenu listing the pattern(s) and their status indicators. When I merged #1058 in locally, that's exactly what I get:
with-1095

So rather than make further changes here, I think it makes more sense to leave this PR as-is and handle the directory flattening issue in 1095, unless there are other state display issues beyond that one.

**Comment by coreylafferty** [comment]
@sghoweri @bmuenzenmeyer now that #1058 is accepted, I believe this PR should be good to go.

**Comment by bmuenzenmeyer** [comment]
i'll need some time to re-read through this

**Pull request merged**
