### PR TITLE
Allow _meta patterns to support any engine

### PR DESCRIPTION
**Pull request by AndrewLeedham**
Addresses: `_meta` patterns being forced to use mustache.

Summary of changes:

- Replaced `".mustache"` literal with `patterlab.config.patternExtension`.
- Allows the use of other engines like handlebars for `_meta` files.

### CODE REVIEW

**Comment by bramsmulders** [comment]
Great idea, but this wouldn't work in some engines. For instance the react engine cannot spit out an incomplete dom tree.

**Comment by cloudsociety** [comment]
Curious if this _meta section would be a better fit in pattern engines themselves. This should allow engines to have better control over their respective file formats. A single method in the engine that either calls multiple meta files or one (react) wrapper file.

Possible PL3.0 wish?

**Comment by bmuenzenmeyer** [comment]
@cloudsociety 
you are right on target. 🎯 

this is basically the idea behind https://github.com/pattern-lab/patternlab-node/issues/611 which is on target for 3.0

I refrained from commenting on this PR until I could think through how (or if at all) `patterlab.config.patternExtension` factors into that solution

**Comment by AndrewLeedham** [comment]
This was more of a hot fix for a project I'm working on, that I thought I'd create a PR for, so I didn't consider all outcomes. I also noticed that the styleguidekit extensions are fixed as `.mustache`, so I can't use [styleguidekit-handlebars-default](https://www.npmjs.com/package/styleguidekit-handlebars-default).

**Comment by cloudsociety** [comment]
@bmuenzenmeyer Awesome! Looking forward to it!

@AndrewLeedham I'll still steal this bit of code so my patterns can build under a single engine in 2.x (having too much fun with Twig/Nunjucks to return to Mustache). Thanks for the share.

-Dave

**Comment by bmuenzenmeyer** [comment]
since this is in the spirit of what we want to do, but the wrong implementation, i am going to close this for now. PL Node 3 will handle this with my above approach

**Pull request closed without merging**
