### PR TITLE
Root out a few more hard-coded paths

### PR DESCRIPTION
**Pull request by geoffp**
That, and kill more `file.substring(2)`s that were a potential source of errors.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Morning @geoffp - looks like this fixes https://github.com/pattern-lab/patternlab-node/issues/222 ?

Since you have it up and running currently, could you do a quick check? Otherwise I can sometime this weekend.

**Comment by geoffp** [comment]
Yeah! Let me look.

**Comment by geoffp** [comment]
I just changed my patterns path to be absolute in `config.json` on this branch, and it seems to work!

**Comment by geoffp** [comment]
Also, having fixed a bug pretty much by accident is a strange and wonderful feeling.

**Comment by EvanLovely** [comment]
I know that `file.substring(2)` is the source of the problem in #222 – that'd be great if this fixed it!

**Comment by bmuenzenmeyer** [comment]
Great news. After a quick check of my own, I will get this merged.

Thanks for the teamwork guys :beers:

**Comment by bmuenzenmeyer** [comment]
This passes a quick check, and is rather simple. Merging. Thanks geoff!

**Comment by geoffp** [comment]
:beer:

**Pull request merged**
