### PR TITLE
Clean rendered html output

### PR DESCRIPTION
**Pull request by gael-boyenval**
Addresses #448 

Summary of changes:

* add js-beautify dependency
* add clean into the render function 

@bmuenzenmeyer 
that's surely not the right place to do it. the tests are failing.
just for you too see. 

maybe it would be more suited to modify ``pattern_assembler.renderPattern ? ``

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@gael-boyenval I think this could likely be moved to just before the writes.

Like around https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/patternlab.js#L388-L395

**Comment by gael-boyenval** [comment]
@bmuenzenmeyer : sorry i didn't saw th message earlier. 
Regarding the templates, i think that the user has full hand on the output, since nothing is transformed, it's just copied. 
I assumed that the user would want to keep them as they was created.

**Comment by bmuenzenmeyer** [comment]
@gael-boyenval You'll see in my additional commit (now on `dev`!) that I am beautifying templates too. 

I plan to release 2.6.0 as an alpha, so I think we can give it a go for a bit and see if there are any problems.

does that sound ok?

**Comment by bmuenzenmeyer** [comment]
> sorry i didn't saw the message earlier.

and this was my first time using the new review interface, so I didn't know if it'd be the same as @mentioning you

**Pull request merged**
