### PR TITLE
Regex cleanup

### PR DESCRIPTION
**Pull request by e2tha-e**
Referencing comment in #251
From @bmuenzenmeyer : 
> Hi @e2tha-e
> 
> Thanks for this contribution - I am nervous though of its eventual collisions with the pattern_engine branch which already refactored a ton of regexes.
>
> @geoffp could you help weigh in?

### CODE REVIEW

**Comment by geoffp** [comment]
For sure, I'll hopefully get time to look at his today.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer @geoffp 
Hopefully we can converge to a point where regexes are both cleaned up and well documented. I haven't looked through the pattern_engine branch, so pardon me if I'm redoing work that has already been done, or colliding in an irrecoverable way.
Here are some things I am trying to accomplish in this pr:

- Allow partial-finding functions to parse strings as well as pattern objects.
- Simplify regexes in the following ways:
  - `( )` === `([ ])` - The square brackets are unnecessary and even excluded on the `findListItems` function.
  - `\w` === `[A-Za-z0-9_]`
  - `(?:` - the 'g' global switch for `String.prototype.match` ignores group capture, so the regex syntax to not capture does nothing but add noise.
  -  `(| )` === `([ ])?` === `( )?` - Use one and use it consistently.
- Strengthen regexes in at least this way:
  - `(\([^\)]*\))` - The old regex searched for an opening parenthesis followed by any number of characters, followed by an optional space, terminating in double closing curly braces. The new regex ensures that parentheses enclose the parameter(s). Then, the regex continues to search for the optional space and double closing curly braces.

[Mozilla docs on RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)

**Comment by geoffp** [comment]
All worthy goals!

Yes, unfortunately, all these functions are Mustache-specific, and have moved to the Mustache engine in the pattern-engines branch. Would you mind re-evaluating this against the regexes in `builder/pattern_engines/engine_mustache.js` in that branch?

**Comment by bmuenzenmeyer** [comment]
I'd go one step further and say that this PR should be closed. I do however love the idea of better documenting the specific regexes, and it looks like some improvements to the regex logic is due. 

I admit, however, that I don't remember how they are documented in the `pattern-engine` branch currently. 

I echo @geoffp in looking to that branch.

---

I am curious as to how you think this PR helps setup a solution for #250 
I have an idea as to how to make this work that seems low-tech but I haven't had time to try it yet.

**Comment by e2tha-e** [comment]
@bmuenzenmeyer It sets up a solution for #250 because the partial finding functions would accept strings as well as the pattern object. And as I got into the weeds of making sure the regexes are matching correctly, I decided that breaking them apart and documenting them would help anyone else who needs to either augment or correct them in the future.

**Comment by e2tha-e** [comment]
I'll definitely look at the pattern_engine branch and see if these changes are more appropriate there.

**Comment by e2tha-e** [comment]
Closing this in favor of #256

**Pull request closed without merging**
