### PR TITLE
UIKit Refactor Part 7: Modal Refactor

### PR DESCRIPTION
**Pull request by sghoweri**
> Note: I’m marking this PR as WIP given that these updates build off of #946 and #949 and any feedback or potential changes there should be reflected here

## Summary
 1st round refactor of Pattern Lab's modal / drawer UI. 

Link to our Pattern Lab instance with these latest UIKit improvements: 
https://uikit-refactor-p7.now.sh/pattern-lab/index.html

<h2>Before (left) and After (right)</h2>

<br>
<br>

### Refactor "Modal" UI; ports to new `<pl-drawer>` component
  - Renames the main "modal" component to "drawer"
  - Simplifies and ports over the component's main UI logic to the new `<pl-drawer>` web component (uses the same Preact-powered base component used in #946 and #949)
  - Improves the overall UI animation by using up the popular [React Animate Height](https://www.npmjs.com/package/react-animate-height) library internally
  - Refactors to use Redux for handling state management -- the component now correctly remembers if a custom drawer height is set

### Add New `<pl-toggle-info>` component
- This PR also adds a new `<pl-toggle-info>` component that's toggles the drawer's state + automatically updates behavior when on viewall pages

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
At least this CI failure is more straightforward

**Comment by sghoweri** [comment]
@bmuenzenmeyer lol - meanwhile, I was arguing with myself... "crap - should I toss these eslint / prettier fixes in, even though I wasn't working on those files..."

image

**Comment by sghoweri** [comment]
@bmuenzenmeyer PR description updated

**Comment by bmuenzenmeyer** [comment]
@sghoweri this is the last PR! let me know when ready for review

**Comment by sghoweri** [comment]
> @sghoweri this is the last PR! let me know when ready for review

@bmuenzenmeyer I just finished pushing up a couple small small fixes after merging in the latest from dev -- should be all set to review!

**Comment by bmuenzenmeyer** [comment]
@sghoweri do the pattern info panels open for you on view all pages? I think this has been broken for a bit, and is perhaps related to https://github.com/pattern-lab/patternlab-node/issues/890

**Comment by sghoweri** [comment]
> @sghoweri do the pattern info panels open for you on view all pages? I think this has been broken for a bit, and is perhaps related to #890

@bmuenzenmeyer yeah, I noticed that the viewall page’s info / code panels weren’t opening — either directly or indirectly related to some Pattern-specific JSON data that appears to be missing from the generated HTML...

I definitely want to make sure we double-check that the accordion-like functionality still works as expected on the viewall pages with these updates here. I know the original version of this PR worked as expected in PL PHP — (at least I know it did before I made a couple updates after further testing this out in the Handlebars demo,  so I’ll double check that 😉).

I suspect the missing viewall page’s JSON data and #890 are likely related and need to get fixed in order to get this on PR wrapped on.

**Comment by bradfrost** [comment]
What's the status of this guy? Just trying to keep stalebot at bay.

**Comment by sghoweri** [comment]
Bump. Still open. I owe @bradfrost some PR review info to get this ball rolling again.

**Comment by bmuenzenmeyer** [comment]
@sghoweri is this ready for review?

**Comment by sghoweri** [comment]
> @sghoweri is this ready for review?

@bmuenzenmeyer besides resolving the merge conflicts, yeah, I think this is still ready to go. 

Definitely would be nice to see the light at the end of the tunnel with this one, #973 and #1008, since that's pretty darn close to where our UIKit implementation is currently at: https://boltdesignsystem.com/pattern-lab/?p=components-overview

**Comment by bmuenzenmeyer** [comment]
[This comment](https://github.com/pattern-lab/patternlab-node/pull/960#issuecomment-433780121) is still relevant - opening an issue for that

**Pull request merged**
