### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**
Closes https://github.com/bradfrost/pl-website-eleventy/issues/23

Summary of changes:

* uses `lerna import` to bring in the new site
* yarnify's everything 
* used to setup netlify docs preview
* also turned off the "header", "Pages changed", "redirect rules", and "mixed content" messages in netlify - so we should be able to declutter that going forward,
* submitted a netlify form to get an open source team account - it will be better long term than using mine

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
also turned off the "header", "Pages changed", "redirect rules", and "mixed content" messages in netlify - so we should be able to declutter that going forward,

**Comment by sghoweri** [comment]
@bmuenzenmeyer +1 on having deploy previews of the Handlebars PL demo as well as a separate deploy previews of the new docs site 👏!

**Comment by sghoweri** [comment]
Just one quick question for @bmuenzenmeyer and/or @bradfrost:

If I'm seeing UI bugs, 404s, old docs info, etc -- should I comment on those here OR should this PR just be focused on moving the bulk of the new docs site work over and we handle any small fixes separately?

I'd prefer us handling those separately but wanted to check with you guys first... didn't want to add a bunch of changes requested if the whole point of this PR was just to add the new docs site to the monorepo and not much else 😜.

**Comment by bmuenzenmeyer** [comment]
@sghoweri IMO this effort was to port over the work already done - not get it perfect

any issues with the site itself should be separate tickets and fixes - now with more preview!

when we're ready, we can start deploying this for real (as in making patternlab.io point to it)

**Comment by sghoweri** [comment]
> @sghoweri IMO this effort was to port over the work already done - not get it perfect
> 
> any issues with the site itself should be separate tickets and fixes - now with more preview!
> 
> when we're ready, we can start deploying this for real (as in making patternlab.io point to it)

Awesome so if that's the case then this gets the go-ahead from my point of view -- good call pulling this in via `lerna import` btw 🙂

**Comment by bradfrost** [comment]
@bmuenzenmeyer @sghoweri what are the next steps to get the site live? Wait for the Netlify open source team stuff to go through and then point the patternlab.io domain over?

**Comment by bmuenzenmeyer** [comment]
assuming https://patternlab-docs-preview.netlify.app/ passes muster and we all agree

1. Change the production branch to `master` instead of `dev`
1. Point the patternlab.io domain over. I've done that in the past - but am unsure if its different when i don't own all ends of the dns config. 🤷 

I assume (2) would be simpler if you have access to the netlify dashboard, which could come with the team or if I can somehow give you direct access to my team

**Pull request merged**
