### PR TITLE
Add starterkit-handlebars-vanilla to CLI

### PR DESCRIPTION
**Pull request by bradfrost**
Added starterkit-handlebars-vanilla to the list of available starterkits; updated some formatting

### CODE REVIEW

**Comment by ringods** [comment]
@bradfrost @bmuenzenmeyer I still have to publish my starterkits on npmjs.com, but once there, can I submit a PR to promote them via the CLI too?

https://gitlab.com/ringods/starterkit-building-blocks
https://gitlab.com/ringods/starterkit-zoho-sites

**Comment by bmuenzenmeyer** [comment]
@ringods I am not sure how best to handle that - as inevitably a list containing too many choices would be daunting for a user to choose from. 

I understand being able to promote community starterkits, plugins, etc would be a big win, however. Right now the [docs site](https://patternlab.io/download.html) links to [this page](https://github.com/pattern-lab/patternlab-node/wiki/Official-&-Community-Plugins) which could certainly be improved too.

do you have thoughts @bradfrost? this is a "product vision" sorta question

**Comment by ringods** [comment]
@bmuenzenmeyer there are only wiki pages for `plugins` and `patternengines`, not for `starterkits`. A new page should be added then where starterkits could be listed then.

Personally, I dislike the use of Github wiki pages because I can't send a PR to contribute content there. **hint** 😉 

If you don't mind writing Asciidoc rather than Markdown, have a look at [Antora](https://antora.org) to create a single site to document multiple versions of multiple components coming from one or more repositories. Nice example: https://docs.couchbase.com/home/index.html

**Comment by bmuenzenmeyer** [comment]
> @bmuenzenmeyer there are only wiki pages for `plugins` and `patternengines`, not for `starterkits`. A new page should be added then where starterkits could be listed then.
> 
> Personally, I dislike the use of Github wiki pages because I can't send a PR to contribute content there. **hint** 😉

You are right the wiki is not a perfect solution, nor the best UX. most of the content there was borne out of a need for speed and I have been concertedly trying to move content into patternlab.io over time. 

@bradfrost is working on some bigger changes to the site - which I hope will better incorporate community 

that being said, I created https://github.com/pattern-lab/patternlab-node/wiki/Official-and-Community-Starterkits with your contributions, they look great!

**Pull request merged**
