### PR TITLE
Show "CSS" and "JS" tabs in code sections

### PR DESCRIPTION
**Pull request by malyw**
Previous Pull Request- https://github.com/pattern-lab/patternlab-node/pull/115
was sent about a year ago and still has not been reviewed despite a positive feedback from developers.
This Pull Request provides updated code for patternlab 1.3.0 and would be closed in two weeks if it has the same destiny as the previous one.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Hi @malyw 
Thanks for this (again). I understand the use case and the utility, and appreciate the work done now twice over to increase the value of PL/Node. I owe you a longer form explanation of where my head's at and what's next for the project. Stay tuned the next few days.

**Comment by bmuenzenmeyer** [comment]
Morning @malyw 

For some time now - the [PL/Node roadmap](https://github.com/pattern-lab/patternlab-node/wiki/Roadmap) has been focused on how to make repo as most know it more maintainable and align with bigger Pattern Lab 2.0 goals found in the PL/PHP parent project.

Dave, Brad, and others are marching towards those goals, and so have I, albeit a bit slowly by the pace of most people's patience. My translation of these goals includes:

- a [core library](https://github.com/pattern-lab/patternlab-node/tree/dev-2.0-core) separated from most if not all frontend chrome
- editions such as [grunt](https://github.com/pattern-lab/edition-node-gulp) and [gulp](https://github.com/pattern-lab/edition-node-gulp) which wrap core, and no longer have to share or juggle configurations, and are themselves more readily consumable
- direct integration with the shared [styleguidekit-assets-default](https://github.com/pattern-lab/styleguidekit-assets-default) and [styleguidekit-mustache-default](https://github.com/pattern-lab/styleguidekit-mustache-default) repositories - **unifying PL/PHP and PL/Node frontends**
- template language-specific pattern engines that can be included a la carte via `npm` for most of this work I have @geoffp to thank
- ingestion of [starterkits](https://github.com/pattern-lab?utf8=%E2%9C%93&query=starterkit-mustache) that speed up prototyping for users and agencies alike
- eventually, a plugin framework to extend functionality in a sustainable way

Every time that I accept a PR like this, it's taking a conscious step away from the goals above, in this case, unified frontend consumption. Other features like [default start pattern](https://github.com/pattern-lab/patternlab-node/pull/270) will instantly regress when we move to consumption, the effort switching to backfilling by means of extending the shared logic or building a plugin + the framework needed. 

In the long time frame it's taken me to get where I am today on [this journey](https://github.com/pattern-lab/edition-node-gulp/issues/2), other PRs have come that are meeting the same fate as this one - they serve a valuable purpose but are either off of main-line development of 2.0 or are dead-ends. That's not to say this work is dead or a waste, it's just that the timing is awful (I am trying to get a 2.0-alpha out by mid June) and my resources are limited (newborn). So much more could be said... about the project, about my communication to you, about expectations in open source... but ultimately I've created something and people expect a certain degree of responsiveness. For the lack of communication, I am sorry. I do feel the roadmap points in the direction I've laid out, however, and has for some time.

I see a few options. You can keep using PL/Node 1.X with this PR locally; it certainly sounds like a nice addition and I am sure you find utility in it. The larger community may not know how to consume it proper, however. I can accept this PR - and push it into a 1.X release, only to have it be ripped out by a 2.X release. That would get people using it if they so chose. Or, we can work together to start planning and building proper plugin support into PL/Node 2.X, which Dave has assured me is the proper home for this functionality in the future.

**Comment by malyw** [comment]
Hey @bmuenzenmeyer, thanks for the extended answer.

After a little thinking regarding that I propose to decline the Pull Request as actually it just adds showing the tabs without logic how they supposed to be used in patterns (in our application we include them separately)- it definitely may confuse the community.
What do you think regarding it?

On the other hand I would be happy to discuss possibility of adding such a functionality (or similar) to the version 2.X as the roadmap promises the bright future.
How can I subscribe to any discussions about it and be up-to-date?

**Comment by bmuenzenmeyer** [comment]
Thanks for your understanding - I am interested in making this a 2.X plugin one day.

One of the best places to stay informed would be https://gitter.im/pattern-lab/node - where myself and @geoff often comment or discuss open items, work in progress, and general stuff too. You (and everyone) is welcome there!

**Comment by malyw** [comment]
Thanks, just joined.
So for now I'm closing the PR.

**Pull request closed without merging**
