### PR TITLE
Load engines flexibly from either the current directory's node_modules

### PR DESCRIPTION
**Pull request by geoffp**
@bmuenzenmeyer, check this out.

This should let us load engines from the core, or from whatever the "current" directory is. This isn't a perfect solution yet, because aside from checking the core, it assumes that the you're launching grunt/gulp/nodeunit/whatever from the root of your edition and looks for engine modules there. Has anyone ever *not* done it that way? Should we be more rigorous?

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Nice work Geoff!

**Comment by bmuenzenmeyer** [comment]
> Has anyone ever not done it that way? Should we be more rigorous?

To answer your questions - no one has ever done what we are doing. Doesn't that sound dramatic! Using PL/Node core with a dependency + editions is new to the Node community, but the consumption patterns we are laying down cowpaths for now make a lot of sense, both for standalone (and perhaps) dependency consumption that we haven't imagined yet. We'll have to see I guess.

**Comment by acariou** [comment]
Hi,

Here is a bit of news about our friends' wedding, just take a look here <http://gupopultu.fortheloveofthebean.com/xyncafmn>

My best to you, arnaud@neolame.com

**Comment by acariou** [comment]
Hi friend! 

I've found  something really lovely and I thought  you might like it too, check it out <http://spifyriko.rubbix.com/e4ypz>

Best wishes, arnaud

**Pull request merged**
