### PR TITLE
Features/incremental build

### PR DESCRIPTION
**Pull request by tburny**
_Addresses #540 _

### Summary of changes:
This is a prototype for recompiling any templates that have been modified since they have been previously built. This works by inspecting the source and output files' modification timestamps.
A pattern is marked as `needs rebuild` if any of its source files was modified after the modification timestamp of the output file. When the template was built and the output was written to disk, it is marked as `clean` to prevent building templates more than once.
### Working

A pattern is recompiled iif
- the template itself was modified
- its data (companion json) was modified
- it is a pseudo-pattern and the according json file was modified
- existing unit tests are running
### Not working yet
- [ ] When using grunt, `patternlab:serve` will wipe the output folder. We can provide a seperate goal.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@tburny thanks for this - and all the comments. Like we discussed - I will start combing through it asap for a 2.8.0-alpha.

In the meantime, if you could attempt to fix the eslint errors that'd help a ton. `npm test` reports them locally too.

**Comment by tburny** [comment]
> In the meantime, if you could attempt to fix the eslint errors that'd help a ton. npm test reports them locally too.

Sure.

**Comment by bmuenzenmeyer** [comment]
@tburny I have started testing this today

**Comment by bmuenzenmeyer** [comment]
@tburny appears broken if `defaultPattern` is not `all`

my test:

`"defaultPattern": "start-welcome",`

**Comment by bmuenzenmeyer** [comment]
scratch that - merging `dev` worked!!!!

**Comment by bmuenzenmeyer** [comment]
* Merged `dev` into `features/incremental-build` locally
* Using `edition-node-gulp` gulpfile
* Testing with `cleanPublic` false, 
* Running `gulp patternlab:serve`

This outputs only changed patterns.

3.2.1.        🚀 >>>>>>>>>>>>>>>>>>>>>🎯 💣

image

**Pull request merged**
