### PR TITLE
Add branching scheme to contribution guidelines

### PR DESCRIPTION
**Pull request by tburny**
Summary of changes: As per Discussion on gitter we updated the contribution guidelines with our branching scheme in order to help new contributors get started quickly.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
This needs to target `dev`

**Comment by bmuenzenmeyer** [comment]
Some conflicts have arisen due to some other edits. Please review - I am excited for this!

**Comment by tburny** [comment]
this stale bot is really annoying

**Comment by tburny** [comment]
Tried my best to resolve all conflicts. let me know if something is missing/wrong.

**Comment by bmuenzenmeyer** [comment]
@tburny with `dev-3.0` now merged into `dev`, we can safely remove that branch in favor of a simpler scheme.

**Pull request merged**
