### PR TITLE
UIKit Refactor Part 8: Nav, Viewport, Header & More!

### PR DESCRIPTION
**Pull request by sghoweri**
Builds off of #960 -- with this PR we're _almost_ completely moved into the new UIKit codebase!

In a nutshell, this PR:
1. Adds a workaround to  a strange Webpack (and possibly Preact) bug when compiling in `production` mode causing some UI components to not show up as expected. While that bug is still present (fix TBD), the build process updates here significantly optimize  what we have -- shaving nearly 1.5MBs off the compiled CSS and JS!
2. Ports over most of the remaining Pattern Lab UI components over to the new refactored codebase.  
  - This including refactoring the navigation / dropdown menu, viewport / iframe, viewport controls, the header, and the contextual menu to all now be rendered as standalone web components (using Preact and SkateJS)
3. Starts the process of breaking apart the massive chunk of styleguide.js logic to start to have things live with the associated component and/or be pulled out into a shared JS utility function that components pull in as a shared dependency
4. Removes most of the remaining Hogan.js templating logic / HTML includes and inline templates since Pattern Lab's UI components can now render their own markup themselves 😉

More to come -- we're almost at the finish line!! 🎉

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
> @bmuenzenmeyer thoughts?

Our last communication still stands, IMO. https://github.com/pattern-lab/patternlab-node/pull/960#issuecomment-433867877

We were hoping to fix #890 before #960. I left some breadcrumbs after having limited time to debug it the last couple weeks. https://github.com/pattern-lab/patternlab-node/issues/890#issuecomment-435891737

**Comment by sghoweri** [comment]
Also bump. I also owe @bradfrost some PR review info on this one as well #drupalcon

**Comment by bmuenzenmeyer** [comment]
seeing some odd behavior in Firefox where the nav renders differently

image

chome:

image


not going to let that stop us

**Comment by bradfrost** [comment]
@bmuenzenmeyer I can take a look at that bug, but would need a refresher on how to fire this up to deal with it!

**Comment by bmuenzenmeyer** [comment]
👋 
I think this will get you there:

```
git checkout dev
npm install && npm run bootstrap
cd packages/uikit-workshop
npm run build //npm run watch may work too but havent tried it
cd ../development-edition-engine-handlebars
npm run pl:serve
```

any changes require rebuilding the workshop - may be easier to open two terminals.

**Pull request merged**
