### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by maxleistner**
Closes #

Summary of changes:
Adds crossorigin Tag to JS file include

### CODE REVIEW

**Comment by sghoweri** [comment]
Do we also need to update the other script tag here? https://github.com/pattern-lab/patternlab-node/pull/1204/files#diff-f39318d71e672540c7fb612b8eacab1eR36

**Comment by maxleistner** [comment]
@sghoweri which other script tag do you mean? I only tried it with the one i changed and after that it worked in Safari, otherwise the site is just a blank white page.

**Comment by maxleistner** [comment]
> Do we also need to update the other script tag here? https://github.com/pattern-lab/patternlab-node/pull/1204/files#diff-f39318d71e672540c7fb612b8eacab1eR36

Do you need anything more in order to merge? :) i really would love to use PatternLab in Safari for testing. Thanks! @sghoweri

**Comment by sghoweri** [comment]
> > Do we also need to update the other script tag here? https://github.com/pattern-lab/patternlab-node/pull/1204/files#diff-f39318d71e672540c7fb612b8eacab1eR36
> 
> Do you need anything more in order to merge? :) i really would love to use PatternLab in Safari for testing. Thanks! @sghoweri

Hang tight -- lemme try testing this on my end (adding a 2nd `crossorigin` attribute to the other `<script type="module">` tag, even if it's just a precaution). Will confirm then lets get this merged!

**Review by sghoweri — APPROVED** [review]
Tested locally (plus updated the other script tag just in case) and everything seems to check out. 👍 

Thanks @maxleistner!

**Comment by sghoweri** [comment]
PR was released with v5.11.1

**Pull request merged**
