### PR TITLE
Update server to support asset change detection

### PR DESCRIPTION
**Pull request by JosefBredereck**
Closes #

#1064 #1130 #957

Needs to be tested on Mac before close #

#1114

Summary of changes:

Fix listed bugs / feature requests and also did a refactoring on the server to match eslint config.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
I tested this the following way:

```
yarn preview:hbs
cd packages/development-edition-engine-handlebars
yarn pl:serve
```

make change to source/css/pattern-scaffolding.css

changes are not reflected in the running app

**Comment by JosefBredereck** [comment]
I just reproduced your test with `npm run pl:serve` and `yarn pl:serve` on `windows`. For me it is working. The problem maybe is, that this isn't written in the console, because `chokidar.watch()` doesn't say which files changed at that point. You can turn this on when you add `logLevel > 0` to your `patternlab.config.serverOptions`. (That behavior was implemented before)

If you change something in `source/css/pattern-scaffolding.css` you will notice the browser reloads. To be sure with this test you could try to add something like this.

```css
body {
   background: red;
}
```

**Comment by bmuenzenmeyer** [comment]
@JosefBredereck i apologize - i tried pulling this fork locally a new way and as it turns out, I had NONE of your changes 😊 

This now is working for me too - tested on Mac and Windows

**Comment by JosefBredereck** [comment]
@bmuenzenmeyer do we close the tickets accordingly?

**Comment by bmuenzenmeyer** [comment]
they should auto close when released - if you dont mind waiting for that

**Pull request merged**
