### PR TITLE
fix(1060): Fix alignment of pattern state dots

### LINKED ISSUE #1060: UIKit Pattern States Dot
I am using Pattern Lab UIKit `v1.0.4`.

##### Expected Behavior
Dots for pattern states should be aligned correctly within the dropdown menu and next to the pattern title.

##### Actual Behavior
Dropdown nav:
image

Pattern title:
image

### PR DESCRIPTION
**Pull request by dcmouyard**
Closes #1060

##### Summary of changes:
Fixes alignment of pattern state dots next to dropdown menu items and pattern titles.

##### Before
image
image

##### After
image
image

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@sghoweri do you have time to review this?

**Comment by sghoweri** [comment]
@bmuenzenmeyer in an hour or so, yep!

**Comment by bmuenzenmeyer** [comment]
going to hop on this one too

**Comment by sghoweri** [comment]
🎉

**Pull request merged**
