### PR TITLE
refactor: corrected some aspects out of eslint feedback

### PR DESCRIPTION
**Pull request by mfranzke**
### Summary of changes:
Fixed some of the aspects that comes out of eslint feedback (via `yarn lint`).

### CODE REVIEW

**Comment by JosefBredereck** [comment]
Do we need the commented-out code, or can we remove it entirely?

**Comment by mfranzke** [comment]
> Do we need the commented-out code, or can we remove it entirely?

@JosefBredereck I was struggling with this question as well. I decided to leave it in as we don't need it at the moment, but as soon as someone might need e.g. the `event` or `options` parameter, they could even already follow the naming (pattern) and don't need to look this up. But that's the only small reason that I came up with that pulled me into the "leave it in direction", whereas I'm fine with both ones, so I could still remove them. What do you think?

**Comment by mfranzke** [comment]
> Do we need the commented-out code, or can we remove it entirely?

I've just decided to remove them. So we should be good to go now.

**Review by JosefBredereck — APPROVED** [review]

**Comment by JosefBredereck** [comment]
PR was released with v5.16.0

**Pull request merged**
