### PR TITLE
chore(build): update Twing dependency

### PR DESCRIPTION
**Pull request by ringods**
Summary of changes:
* Update Twing engine to v5.0.1

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Does the 4 to 5 upgrade impact end users?

**Comment by ringods** [comment]
@bmuenzenmeyer I tested it locally and there were no regressions AFAICS. But one of the fixed issues regarding relative imports triggered me to test it regarding the issue I asked your help for.

**Comment by ringods** [comment]
@bmuenzenmeyer could this get merged?

I am hoping to test `engine-twig` with a newer `twing` library aiming to find the cause for #1201

**Comment by bmuenzenmeyer** [comment]
I saw the other message about uneven head and foot calls. Does this engine or the twig library render as promises? 

(Thanks for patience recently,  I'm swamped at work)

**Comment by ringods** [comment]
Yes it does. See the section `Rendering Templates` from the docs: https://nightlycommit.github.io/twing/api.html

**Comment by sghoweri** [comment]
PR was released with v5.11.1

**Pull request merged**
