### PR TITLE
Fix issues with multiple inline svgs in live-server injection

### LINKED ISSUE #1011: Multiple inline svgs break html files
I am using Pattern Lab Node v3.0.1-alpha.0 on Windows, with Node v10.15.3, using a Custom Edition.

I am having the same problem that has been reported by issue #272 on tapio/live-server's main repo. [tapio/live-server's main repo](https://github.com/tapio/live-server/issues/272).

A [PR has been submitted](https://github.com/tapio/live-server/pull/279) but not merged.

I would be willing to create a PR to fix the problem on this repo.

### PR DESCRIPTION
**Pull request by mdmccarley89**
Sets the content-length correctly based on the total number of SVGs contained in the document.

Closes #1011

### CODE REVIEW

**Comment by dnwhte** [comment]
I've tested the solution. Looks good to me. @sghoweri, any thoughts on merging this in?

**Comment by sghoweri** [comment]
👍can you help check this out when we publish the next beta later today?

**Comment by dnwhte** [comment]
Will do.

**Comment by sghoweri** [comment]
@dnwhte thanks - really appreciate it!

**Pull request merged**
