### PR TITLE
#349: Use js-yaml to parse json, yaml, and yml config files

### PR DESCRIPTION
**Pull request by fillerwriter**
Addresses #349 

Summary of changes: Refactored buildPatternData to use js-yaml library to parse all the config files. Added a unit test to ensure we're picking up the appropriate files.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
hello @fillerwriter this is certainly a welcome surprise! thanks for this initial bit of work - I am excited to round out PL Node support with yaml.

**Comment by fillerwriter** [comment]
@bmuenzenmeyer No problem. I've swapped out the consts that fall outside the additional work I've done.

**Comment by fillerwriter** [comment]
@bmuenzenmeyer Apologies for letting this sit for a bit. I ended up refactoring the logic for loading the config files into helper functions, and swapped out the implementation across the board. I'd like to tighten up the implementation before merging in. If you have any input, I'm interested in hearing it. :-)

**Comment by fillerwriter** [comment]
Sweet. I like `data_loader` as a name, and can definitely switch. The other thing I'm wanting to do is adjust the footprint of the methods so that fs can be an optional dependency, and ensuring we have at least minimal testing setup for the new code. 

I'm hoping to get to this today/tomorrow.

**Comment by fillerwriter** [comment]
@bmuenzenmeyer Ready for review. Thanks for your patience.

**Comment by bmuenzenmeyer** [comment]
Great work! Sorry this took so long!

**Pull request merged**
