### PR TITLE
Fix pattern lab create script

### LINKED ISSUE #1157: npm create pattern-lab with specified directory and starterkit broken
install starterkit needs to be `projectDir` aware

workaround:

`mkdir my-project && cd my-project` before you `npm create pattern-lab`
then, specify the current directory as the install target

### LINKED ISSUE #1247: Deprecate `checkAndInstallPackage` and `fetchPackage`
I'm hearing from the core maintainers that everything in Patternlab should be(come) more explicit. In the uikit handling (#1225, #1246), I'm making the package name and explicit requirement and I'm loading resources via de NodeJS resolver.

NPM, Yarn v1, Yarn v2 and pnpm don't all have the same "package" lookup strategy. Yarn v2 with PnP even wants to get rid of the complete `node_modules` folder(s). The reason to work via the NodeJS resolver is that it doesn't matter anymore which package manager our users are using.

As part of the above work, I also bumped into an issue with starterkits. The CLI has the option to install a starterkit based on the package name. But if it isn't found, there is a check to detect which package manager is used and a subprocess will install the required package. But installing the package in a subprocess will, given the different package managers, not always make the package available in the parent process.

So, a starterkit should be a dependency of the project at hand if the lookup happens via the resolver. That is why I want to get rid of the functions `checkAndInstallPackage` and `fetchPackage`:

https://github.com/pattern-lab/patternlab-node/blob/f4d6bd1fd2afd3cb4403350f24d747e44c54cd6c/packages/cli/bin/utils.js#L125-L166

@sghoweri @JosefBredereck

### LINKED ISSUE #1257: npm create pattern-lab with edition twig throws an error and hangs
I am using Pattern Lab Node `v.5.13.1` on `Mac`, with Node `v14.9` (also in earlier node version vom v12 on), using the `Twig Edition`.

##### Expected Behavior

Clean install of the pattern-lab twig demo in any directory

##### Actual Behavior

Installation of the twig edition throws actually an error and hangs.

```
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig(node:66426) UnhandledPromiseRejectionWarning: Error: Cannot find module '@pattern-lab/edition-twig/package.json'
Require stack:
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/ask.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/cli-actions/init.js
- /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at resolveFileInPackage (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:10:18)
    at resolvePackageFolder (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:18:23)
    at resolveDirInPackage (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:26:20)
    at /Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/install-edition.js:38:7
    at Generator.next (<anonymous>)
    at spwn (/Users/Joville/.npm/_npx/66125/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js:75:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:66426) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66426) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠦ ⊙ patternlab → Installing edition: @pattern-lab/edition-twig
```

##### Steps to Reproduce

1) `npm create pattern-lab`
2) `? Please specify a directory for your Pattern Lab project. ./`
3) `? What templating language do you want to use with Pattern Lab? Twig (PHP)`
4) `? What initial patterns do you want included in your project? Twig (PHP) demo patterns (full demo website and patterns)`
5) `? Are you happy with your choices? (Hit enter for YES)? Yes`

### PR DESCRIPTION
**Pull request by JosefBredereck**
While changes were made to the package resolving, some errors appeared. This should fix these errors.

Closes #1157
Closes #1247
Closes #1257

Summary of changes:
Updated execa
Added CWD to the installation of packages

### CODE REVIEW

**Comment by sghoweri** [comment]
@JosefBredereck @ringods what's the status on this one? 

Is there something holding this back from getting released or can we get this hotfix out the door ASAP? 

Asking for a friend (CC @bradfrost)! 😉

**Comment by JosefBredereck** [comment]
@sghoweri from my side its ready.

**Comment by ringods** [comment]
@JosefBredereck if this makes sure that `npm create` is no longer running in a temporary folder, but from the current folder, then I expect my [workaround mentioned here](https://github.com/pattern-lab/patternlab-node/issues/1257#issuecomment-688489055) is no longer needed, right?

If this fixes this, then all fine by me too.

**Comment by JosefBredereck** [comment]
Yes exactly that it is doing.

**Review by ringods — APPROVED** [review]

**Comment by JosefBredereck** [comment]
@sghoweri @ringods that did not fix it (╯°□°）╯︵ ┻━┻
Sadly
I will investigate further

**Pull request merged**
