### PR TITLE
fix(engine_twig_php): Twig incremental rebuilds

### PR DESCRIPTION
**Pull request by zhawkins**
Fixes issue where edits to twig files included in parent do not appear
until the parent file is updated.

Closes issue #1015

Summary of changes:
- Updates regex patterns to match multi-line includes, extends and embeds. (See examples on line 123)
- Updates regex patterns to match both single and double quotes.
- Adds `findPartials` support which should find any partials that contain include, embeds or extends.
- Adds `findPartial` support which should take the include/embed/extend and use any provided namespaces to resolve a partial file. That partial file is used to return a pattern key.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
I dont have the bandwidth to check out these Twig PRs, can someone else please review?

**Comment by sghoweri** [comment]
> I dont have the bandwidth to check out these Twig PRs, can someone else please review?

🙋‍♂@bmuenzenmeyer starting to take a look at this!

**Comment by sghoweri** [comment]
Fixed it! Now the shorter hand Twig namespace syntax works too (plus no missing templates / warnings when compiling).

Pushing this update up shorty so we can get this merged. 🙂

**Comment by zhawkins** [comment]
Awesome! Thanks for doing that! 😎

**Pull request merged**
