### PR TITLE
update serve-index to 1.9.1 - fixes #982

### LINKED ISSUE #982: [Vulnerability] Regular Expression Denial of Service
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ negotiator                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >= 0.6.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @pattern-lab/cli                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @pattern-lab/cli > @pattern-lab/core >                       │
│               │ @pattern-lab/live-server > serve-index > accepts >           │
│               │ negotiator                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/106                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

Please bump dependency `serve-index` to 1.8.0 or up in the `live-server`. This will result in negotiator v0.6.1 to be picked up.

### PR DESCRIPTION
**Pull request by malcomio**
Closes #982

Summary of changes:
Update serve-index from 1.7.2 to 1.9.1

### CODE REVIEW

**Comment by malcomio** [comment]
needs more local testing...

**Comment by ringods** [comment]
@malcomio did your testing detect any regressions with this version bump?

**Comment by malcomio** [comment]
haven't noticed any problems, although it hasn't had heavy use

**Comment by ringods** [comment]
@malcomio @EvanLovely can this be merged?

**Comment by sghoweri** [comment]
@ringods I'm fine having us merging this in as part of the next beta release (and can keep testing to see if there's any unexpected side-effects from this)

**Pull request merged**
