### PR TITLE
Add support for pseudo patterns for example button~variant.json

### PR DESCRIPTION
**Pull request by david-moldenhauer**
Closes #

Summary of changes:
Adds support for pseudo patterns for example button~variant.json

### CODE REVIEW

**Comment by coreylafferty** [comment]
Would (or could) this work with YAML files as well as JSON?

**Comment by david-moldenhauer** [comment]
it should work on YAML as well as JSON

**Comment by sghoweri** [comment]
Bump - want to make sure this doesn’t get lost

**Comment by zhawkins** [comment]
I believe https://github.com/pattern-lab/patternlab-node/pull/1046 is a replacement for this PR. 

Since that resolves the variant issues with psuedo patterns I _think_ this can be closed.

**Comment by sghoweri** [comment]
> I believe #1046 is a replacement for this PR.
> 
> Since that resolves the variant issues with psuedo patterns I _think_ this can be closed.

Sounds good! Thanks again for your help @zhawkins!

**Pull request closed without merging**
