### PR TITLE
fix(plugin): correct spelling error and function locations

### LINKED ISSUE #916: Installing a plugin results in an error when running patternlab.
I am using Pattern Lab Node 3.0.0-alpha.16 on Mac, with Node v10.3.0, using a Vanilla Edition. I used starterkit-mustache-demo. 

##### Expected Behavior
Pattern Lab should build successfully.
##### Actual Behavior
It fails with this error:

> plraw@1.0.0 patternlab /Users/abailey/Sites/plraw
> patternlab "build"
> 
> Pattern Lab Node v3.0.0-alpha.16
> Pattern Engine mustache: good to go
> ⊙ patternlab → Error: ENOENT: no such file or directory, scandir 'plugin-'

##### Steps to Reproduce
- Install Pattern Lab Node Core using 0 to 60mph instructions with edition node and
starterkit-mustache-demo.
- "npm run patternlab build" to confirm it builds successfully (it does)
- install plugin using "npm run patternlab -- install --plugins @pattern-lab/plugin-tab"
- "npm run patternlab build" again. This time it fails with above error.

I also after this tried installing the plugin using "npm install plugin-node-tab --save" but that didn't work.

May or may not be relevant, but out of curiosity I created a directory called "plugin-" and put it in the root of the project. When I did the build command again I got:
> ⊙ patternlab → TypeError: undefined is not a function

instead of the scandir error. I tried moving the plugin-tab folder to the root though and that didn't work.

### PR DESCRIPTION
**Pull request by enigmatic**
Closes #916

Summary of changes:
 * Corrected several typos that broke plugins
 * fixed the plugin-tab naming inconsistencies

### CODE REVIEW

**Comment by enigmatic** [comment]
FYI, this does not fix the plugin-tab, I'm still trying to figure out what's going on with the lack of a Panels global in the generated code

**Comment by enigmatic** [comment]
@bmuenzenmeyer was assigned the issue, so probably should get notified as well

**Comment by enigmatic** [comment]
Had to abandon the global Panels research and get back to **real work**.  But importing plugins looks like it works, just plugin-tab itself seems broken.  I don't know enough about the plugin system to know why.

**Comment by aleksip** [comment]
@sghoweri This looks good to me, and seems like an essential step to get plugins to work.

**Comment by aleksip** [comment]
@enigmatic Oops. Looks like I merged the latest changes from the main repo to your fork, didn't mean to do that, sorry. Hopefully no harm done.

**Comment by bmuenzenmeyer** [comment]
I am going to re-point this towrd the `🔌` branch where I will start working on making the plugin system what folks expect!

**Pull request merged**
