### PR TITLE
update lineage_hunter - refactor

### PR DESCRIPTION
**Pull request by mateuspv**
**Target the `dev` branch!**
Summary of changes:
I remove Closures("(function () { ... })()") since node will not export any that are not implicit with `module.exports`. Also removed some nested functions.

Thanks!

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Hi @mateuspv 

it looks like this optimization could be applied to other builder/ files besides list_item_hunter.js, is that correct?

**Comment by mateuspv** [comment]
Hi @bmuenzenmeyer, Yes. You can remove the "main code" from inside the closure:
(function() {
/* main code here */
})()

**Comment by bmuenzenmeyer** [comment]
Thanks for the clarification. I'd rather see all the extraneous closures removed at once for consistencies sake. If you feel like tackling that, please do so. Else this might get prioritized a bit further down the pile.

**Comment by geoffp** [comment]
I was just [researching this issue](http://stackoverflow.com/a/26083615/446564), and I agree that we should remove them all. 

@mateuspv, if you're up for doing all of them, that would be amazing, but if you don't want to, I could do it was part of a larger whitespace & indentation cleanup.

**Comment by mateuspv** [comment]
@geoffp I'm sure when I will do it =/, so feel free to do..

**Comment by bmuenzenmeyer** [comment]
I second rolling it into https://github.com/pattern-lab/patternlab-node/issues/264

**Comment by bmuenzenmeyer** [comment]
Added as a todo item to https://github.com/pattern-lab/patternlab-node/issues/264.

Closing this.

**Pull request closed without merging**
