### PR TITLE
feat: integrate @hadl/patternlab-plugin-pattern-wrap into core

### LINKED ISSUE #1432: Integration of @hadl/patternlab-plugin-pattern-wrap into core
As discussed with Maximilian and Josef my integration of the plugin @hadl/patternlab-plugin-pattern-wrap (https://github.com/hadl/patternlab-plugin-pattern-wrap) into the core.

### PR DESCRIPTION
**Pull request by hadl**
Closes #1432

### CODE REVIEW

**Comment by JosefBredereck** [comment]
@hadl thank you for your contribution. 🚀  I would like to request some tests for this change.
I will try to look into the changes after holidays.

**Comment by hadl** [comment]
@JosefBredereck great, thanks.

i would suggest to do the documentation etc if this is ready to merge and no further changes need to be done.

**Review by JosefBredereck — APPROVED** [review]

**Comment by JosefBredereck** [comment]
> @JosefBredereck great, thanks.
> 
> i would suggest to do the documentation etc if this is ready to merge and no further changes need to be done.

Do you mean you want to open another PR or within that one?

**Comment by hadl** [comment]
@JosefBredereck test and docs added. Hope everything fits your needs.

There was broken link in packages/docs/src/docs/advanced-config-options.md:213 - this is fixed too

**Review by JosefBredereck — APPROVED** [review]

**Pull request merged**
