### PR TITLE
Change var to const or let

### PR DESCRIPTION
**Pull request by benhalverson**
Addresses #598 

Summary of changes:
This is the start of converting var's to const or let. 
Looking for some initial feedback

### CODE REVIEW

**Comment by raphaelokon** [comment]
LGTM. One thing worth doing would be adding http://eslint.org/docs/rules/prefer-const to the `.eslintrc` and rerun the the lint step. This way we would prevent accidentally  adding `var` in future when merging PRs.

**Comment by bmuenzenmeyer** [comment]
Awesome work.  Since this is so significant a change I am going to point it to dev-3.0

**Comment by bmuenzenmeyer** [comment]
@benhalverson 
This is a great step in the right direction, thanks!
I merged this with `dev-3.0` - all still runs. Turning on prefer-const as Raphael suggests yeilds 100+ errors. Are you willing to fix ?

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Those lint *errors* are just guides and does not always reflect appropriateness – just a compass. Awesome job @benhalverson

**Comment by bmuenzenmeyer** [comment]
Sorry I was not articulate.
If we turn prefer-const on permanently and do not address errors, future
lint efforts are harder to parse through. I am likewise ecstatic with the
work done so far.

**Comment by benhalverson** [comment]
Thanks Guys. Yes I can work on the rest. I was going to ask about changing the vars in the tests also. Should that be another issue?

**Comment by bmuenzenmeyer** [comment]
The tests are not linted due to their inconsistent style from years of development. I'd leave them out of scope for now and focus on the main library. If you want to do it as another issue, you are most welcome.

**Comment by benhalverson** [comment]
i didn't have these conflicts on my machine. @bmuenzenmeyer I'll see if I can resolve them.

**Comment by bmuenzenmeyer** [comment]
@benhalverson will fix this on my end tomorrow morning

**Comment by bmuenzenmeyer** [comment]
@benhalverson I am rolling this into #610 as I fought with it enough here and there today and I think it needs a bit more oomph.

**Comment by benhalverson** [comment]
Ok. Thanks

**Comment by bmuenzenmeyer** [comment]
With #610 done, I think this is in limbo. Please see my other comments.

**Comment by benhalverson** [comment]
@bmuenzenmeyer do I need to do anything here?

**Comment by bmuenzenmeyer** [comment]
@benhalverson mostly asking if you are okay with me closing. I had to merge it into work already apart of `dev-3.0`. The rub is for some reason I don't see any of your commits (meaning you won't get "credit" for the work).I think the circumstances of the merge somehow qualified all the commits as my own? This is the first time this has happened.

I will still display this PR and your name in the changelog and release notes, as you did great work!  
Are you okay with that?

**Comment by benhalverson** [comment]
Yep it's ok with me

**Pull request closed without merging**
