### PR TITLE
Workaround / Fix for Top-level Viewall + Markdown Issue

### PR DESCRIPTION
**Pull request by sghoweri**
Workaround / possible fix to address PL Node viewall page issues when compiling standalone markdown files in top-level pattern folders. This update tweaks how `injectDocumentationBlock` handles existing "pre-processed" documentation data (ie. markdown files) by processing all patterns the same way (`new Pattern.createEmpty`) but still include the pattern description data if it already exists.

Addresses #890 and #970.

### CODE REVIEW

**Comment by sghoweri** [comment]
@bmuenzenmeyer -- heads up, looks like this bug might be much more complex than I thought. 

While it looks like this particular update helps with a pattern folder a few levels deep, it looks like things still get wonky if there's heavily nested patterns =/

## Works
image

## Broken
image

Without doing quite a bit more reverse engineering (or refactoring), I'm not sure how much further I can take this myself -- any ideas on where I should be digging around?

**Comment by sghoweri** [comment]
@bradfrost what should we do here? Merge this potential fix in? Hold off?

**Comment by bradfrost** [comment]
@sghoweri hmmm I unfortunately don't think I can speak to this regarding what to do with it, this one seems more @bmuenzenmeyer's department.

**Comment by bmuenzenmeyer** [comment]
@sghoweri lemme see if i can recover where I was with this

**Comment by mfranzke** [comment]
Ooohh nooo, fight this bot!

**Comment by bmuenzenmeyer** [comment]
I want to use https://patternlab-handlebars-preview.netlify.com/ to re-assess if this is still a problem

**Comment by bmuenzenmeyer** [comment]
@sghoweri with our recent conversation revealing that top-level [pattern type (atoms, molecules) documentation was never implemented](https://github.com/pattern-lab/patternlab-node/issues/415), I would rather we look at it holisitically rather than patch

please reopen if you disagree

**Pull request closed without merging**
