### PR TITLE
WIP: improvement(docs): added iframes for the pages #1172

### LINKED ISSUE #1172: New Docs Update: Replace Demo Screenshot Placeholders
https://patternlab.io/demos/

A2ECDBC3-21EB-4817-B847-B6864B2C76CE

### PR DESCRIPTION
**Pull request by mfranzke**
Closes #1172

Summary of changes:
Added iframes for the linked pages as a preview ~~screenshots for all the placeholders by the linked websites via an online service.~~

~~Configuration options: https://www.thum.io/documentation/api/url#options~~

### CODE REVIEW

**Review by sghoweri — COMMENTED** [review]
I'm kind of on the fence with this one @mfranzke (albeit, super cool screenshot-generate service and I love the idea of screenshots like these being auto-updating, even if that's only at build-time!).

Given that this is a paid service with no Open Source option listed, don't we run the risk of these auto-requested / generated screenshots breaking unexpectedly down the road?

**Comment by mfranzke** [comment]
@sghoweri, agreed. I just recognized the following sentence:
"You can use up to 1000 impressions per month completely free, without even signing up!"

So I'll try to find another service / solution for this topic.

**Comment by JosefBredereck** [comment]
@mfranzke I added another version. What do you think about that? (If netlify wouldn't fail)

I also removed the "old" pattern lab starters because we are not supporting that anymore.

**Comment by JosefBredereck** [comment]
Now we are talking. 👍

**Comment by mfranzke** [comment]
> @mfranzke I added another version. What do you think about that? (If netlify wouldn't fail)
> 
> I also removed the "old" pattern lab starters because we are not supporting that anymore.

@JosefBredereck I'm loving that approach, great idea ! Let's do this.

**Review by JosefBredereck — APPROVED** [review]

**Comment by JosefBredereck** [comment]
Released with [v5.13.1](https://github.com/pattern-lab/patternlab-node/releases/tag/v5.13.1)

**Pull request merged**
