### PR TITLE
Convert engine_handlebars_tests.js to use tape

### PR DESCRIPTION
**Pull request by alexbenic**
Addresses #517

### CODE REVIEW

**Comment by alexbenic** [comment]
It seems to fail against node v4.6. Not sure why, will take a look today.

**Comment by alexbenic** [comment]
I can't reproduce the error using:
- ```node -v``` : ```v4.6.0```
- ```npm --version ``` : ```2.15.9```
- ```nvm --version ``` : ```0.32.0```

I have tested both with and without engines installed. It works as intended.

I could refactor it to use ```tap```, but conditional testing will be less... elegant, since I haven't been able to find ```test.only``` equivalent in ```tap```.

**Comment by bmuenzenmeyer** [comment]
trying to manually restart that job on travis as a first step

**Comment by bmuenzenmeyer** [comment]
pulled this down local - also getting an error - i guess that's a good thing

**Comment by alexbenic** [comment]
I will refactor one test to use ```tap``` and see how it goes.

**Comment by bmuenzenmeyer** [comment]
@alexbenic glad to see this working - one of my todos will be to convert them all to tap so as to further remove grunt from the equation. thanks for checking this out and getting it working

**Pull request merged**
