### PR TITLE
BREAKING-CHANGE: Deprecate ordering by file-prefix ##-

### LINKED ISSUE #1028: Remove Pattern Type, Subtype, and Pattern Order mechanic using ##- in the filename
As documented in our [feature review](https://github.com/orgs/pattern-lab/projects/3#card-23742746) I am planning to remove the `00-atoms/` means of ordering in favor of markdown.

* Metadata should not be baked into file names - it mucks with git history
* It complicates the code immensely, leading to issues like #890

When this issue is finished, specify `order` within the optional markdown frontmatter to specify the order in which PL generates the UI.

**source/_patterns/atoms.md**
``` yaml
order: 1
---
# Atoms are small
```

**_patterns/atoms/buttons.md**
``` yaml
order: 1
---
# Buttons are the next big thing.
```

**_patterns/atoms/buttons/calltoaction.md**
``` yaml
order: 3
---
# Try a click today
```

Related: https://github.com/pattern-lab/patternlab-node/issues/415

### LINKED ISSUE #1176: Deprecate Pattern Type, Subtype, and Pattern Order using ##-Syntax
Converted from https://github.com/orgs/pattern-lab/projects/3

### PR DESCRIPTION
**Pull request by JosefBredereck**
Closes #1028
Closes #1176

Summary of changes:

Remove the ability to sort files and folders by the ##- prefix. Since that approach could become unhandy when you want to reorder your patterns.

(Reopening to split changes in code and starter kit file changes)

### CODE REVIEW

**Comment by aleksip** [comment]
Curious about a few things related to this PR:

- Does this also add the ability to specify the order in front matter?
- Will there be a transition period during which both methods are supported, so everything would be ordered based on possible file prefix first, and then based on possible front matter?
- Is there any estimate for when this will be in a release?

**Comment by JosefBredereck** [comment]
>     * Does this also add the ability to specify the order in front matter?

yes

>     * Will there be a transition period during which both methods are supported, so everything would be ordered based on possible file prefix first, and then based on possible front matter?

yes, there will be a transition phase

>     * Is there any estimate for when this will be in a release?

maybe at the end of september

**Comment by aleksip** [comment]
Awesome, thanks!

**Comment by JosefBredereck** [comment]
See my comments on #1237 for further information on testing.

**Pull request merged**
