### PR TITLE
Ensure that patterns in direcorties greater than 2 levels deep from s…

### PR DESCRIPTION
**Pull request by david-moldenhauer**
…ource are sorted to the next possible parent directory.

This allowes file structures like:
00-atoms/03-controls/00-button
 - button.pattern
 - button.md
 - button.scss
 - button.js

Closes #

Summary of changes:

### CODE REVIEW

**Comment by coreylafferty** [comment]
Is it an easy change to make this so it will nest components with the same name as their folder under the same parent menu item in the PL menu?  For example, I've tried this folder structure:
```
/03-components/grid/grid.twig
/03-components/grid/grid--2col.twig
/03 components-grid/grid--3col.twig
```
What comes out in the PL menu is:
- components
-- grid (folder)
---- grid 2 column (component)
---- grid 3 column (component)
-- grid (component)

Ideally it would be:
- components
-- grid (folder)
---- grid (component)
---- grid 2 column (component)
---- grid 3 column (component)

Currently I've just named the folder 'grids' and then it properly nests them, so I'm assuming it's a conflict with the filename and folder name being the same.

**Comment by david-moldenhauer** [comment]
@coreylafferty 
Patternlab only supports 2 levels under the pattern-source directory. What this minor change does is remove all deeper folder information and save the reference in the second level parent folder.
The pattern name is still generated by the pattern file name.
so 'first-level/second-level/third-level/patternfile.ext' becomes 'first-level/second-level' + 'patternfile'
meaning the third-level folder will be ignored as would a fourth-level and so forth.

**Comment by coreylafferty** [comment]
@david-moldenhauer Apologies -- I should have looked at this closer.  At first glance I thought this was further improvements to the initial change to support 2 levels from PR #992

**Comment by sghoweri** [comment]
> @david-moldenhauer Apologies -- I should have looked at this closer. At first glance I thought this was further improvements to how menu items are nested from the first or second level folders after the initial change to support two levels from PR #992

FWIW, I'd really like to see us add support for deeper levels of nested navigation!

**Comment by david-moldenhauer** [comment]
BTW. The tests fail because they are set up with more than 2 levels deep file structure (as is currently not supported). Is this a theoretical thing in case an extra level does get support at some time? As they are now the tests would fail but run on the second navigation level in the browser or succeed and not run in the browser at all.

**Comment by bmuenzenmeyer** [comment]
> Is this a theoretical thing in case an extra level does get support at some time? As they are now the tests would fail but run on the second navigation level in the browser or succeed and not run in the browser at all.

This and your commit comment show me the stretch marks and crow's feet of open source over time. I am not familiar with how that particular code evolved during my time away, but I am assuming it was #992

I plan to review this code in earnest soon

**Comment by bmuenzenmeyer** [comment]
Ugh I merged this wrong

**Comment by JosefBredereck** [comment]
As I see now this pull was not thought of correctly. The Idea behind that was never to have deeper nested folders. The original idea was completly ignored and removed. Even the test where changed that they pass the given behavior, not the wished one. 

Please see the following discussion and pull request for more information
[Added separated pattern-folder support](https://github.com/pattern-lab/patternlab-node/pull/992)

**Comment by bmuenzenmeyer** [comment]
hi @JosefBredereck 

I am sorry that I've mismanaged this feature - I came into it late and tried my best to play catch up - but clearly fell short. I need people like you with consistent, long-lasting interest and ability to help keep the codebase in check!

**Comment by JosefBredereck** [comment]
@bmuenzenmeyer no problem. I was abstinent by myself and just tipped over that right now. I also saw an issue related to that change.

To get this change correctly. The intention was to move sub-dirs to the nearest top level if you accidentally added it or want to structure your files. At this point, we have to differentiate between pattern definition as directory and just a folder with patterns for organizational purposes.

```
- molecules/
  - blocks/
    - media-block/
      - media-block.md
      - media-block.mustache

    - some-random-folder
      - random-comp1.json
      - random-comp1.md
      - random-comp1.mustache
      - random-comp2.json
      - random-comp2.md
      - random-comp2.mustache
      - another-random-folder
        - random-comp3.json
        - random-comp3.md
        - random-comp3.mustache
        - random-comp4
          - random-comp4.json
          - random-comp4.md
          - random-comp4.mustache
        ...

    - button/
      - button.md
      - button.mustache
      - button~primary.json
    - jumbotron.md
    - jumbotron.mustache
  - heading/
    - heading.md
    - heading.mustache
  - link.mustache
  - link.md
- card/
  - card.md
  - card.mustache
...
```

Given this tree, it should result that `some-random-folder` and `another-random-folder` would be removed and the components `random-comp1.mustache`, `random-comp2.mustache`, `random-comp3.mustache` and `random-comp4.mustache` will be attached to blocks as long as deeper nesting is not supported. This can go deep endlessly. Also be aware that deeper nesting could contain a nested pattern.

```html
<ol>
  <li>Molecules
    <ol>
      <li>Blocks
        <ol>
          <li>Media Block</li>
          <li>Button</li>
          <li>Button Primary</li>
          <li>Jumbotron</li>
          <li>random-comp1</li>
          <li>random-comp2</li>
          <li>random-comp3</li>
          <li>random-comp4</li>
        </ol>
      </li>
      <li>Heading</li>
      <li>Link</li>
    </ol>
  </li>
  <li>Card</li>
</ol>
```

While this is the case you always have to keep in mind that the factory can still find the associated `.md `and `.json` files.

I'm working on implementing this behavior right now and hopefully will add a pull request this weekend.

**Pull request merged**
