### PR TITLE
renamed config.json to patternlab-config.json for better consumption

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**
Address #192 by renaming config.json to patternlab-config.json

### CODE REVIEW

**Comment by geoffp** [comment]
nice :+1:

**Comment by bmuenzenmeyer** [comment]
Hope its not too tough to merge all this into `pattern-engines`. Between the builder > lib move and the whitespace cleanup and this there is certainly a lot of change a'comin'

:rocket:

**Comment by geoffp** [comment]
Actually, I should go check that out now and merge dev into p-e. I did do the merge after the big whitespace cleanup and it *sucked*. I don't know what we'd do without all the unit tests.

**Comment by bmuenzenmeyer** [comment]
I had some luck with git/SourceTree understanding `builder/*js` move. Hope it's not too rough on ya.
All baby steps toward https://github.com/pattern-lab/patternlab-node/issues/281 - now with an official issue cause why not

**Comment by geoffp** [comment]
Checking out the merge situation now. I did do the merge after the big whitespace cleanup and it *sucked*. I don't know what we'd do without all the unit tests.

**Comment by geoffp** [comment]
Hey, the big merge exposed a nasty bug in pattern-engines: I was doing the wrong thing with underscore-prefixed pattern files.

**Pull request merged**
