### PR TITLE
Next Release: v3.0.0-beta.2

### PR DESCRIPTION
**Pull request by sghoweri**
# Summary of changes:

## Updates & Improvements
- Updated .prettierignore and anded ignore path to npm prettier script #945 
- Add cachebuster to allFooterData #947 
- Added + updated the codeowners file via #950 and #965 
- Updated package.json to >=8 + added .nvmrc file via #951 
- UIKit refactor updates and improvements via #946, #949, and #966!
  - Adds UI Controls for toggling light / dark mode + horizontal / vertical layouts
  - Refactors / ports over many of the UIKit components to web components (via Preact + SkateJS)
- Added `yml` / `yaml` support for psuedo patterns (in addition to JSON) via #981

## Fixes
- Partial fix for path resolution #969 
- Fix for find all patterns (including pseudo patterns) #978
- Fixed broken package links within the repo #979

### CODE REVIEW

**Comment by sghoweri** [comment]
@bradfrost three big items we need to decide on before potentially cutting the next beta release:

1. Do we want to try and get [this potential fix](https://github.com/pattern-lab/patternlab-node/pull/977) for the long-running View All issue merged down to dev
2. What about the next 2 rounds of UIKit updates (also still waiting to get merged down):
  - https://github.com/pattern-lab/patternlab-node/pull/960
  - https://github.com/pattern-lab/patternlab-node/pull/973
3. Cutting a new release (ie. merging down to master before publishing something) requires someone to review and OK this. Who?

**Comment by bmuenzenmeyer** [comment]
👋 

Thanks for stepping up @sghoweri - it's clear your passion and energy will help us all!

As for https://github.com/pattern-lab/patternlab-node/pull/977 I was reluctant to merge that once you stated you observed deeper issues, and I had a slow-cooking fix myself, but nothing concrete yet.

As for releasing, I can help teach you. Can we have a chat on Friday?

**Comment by sghoweri** [comment]
> 👋
> 
> Thanks for stepping up @sghoweri - it's clear your passion and energy will help us all!
> 
> As for #977 I was reluctant to merge that once you stated you observed deeper issues, and I had a slow-cooking fix myself, but nothing concrete yet.
> 
> As for releasing, I can help teach you. Can we have a chat on Friday?

Thanks @bmuenzenmeyer - that sounds great! Just let me know what time you want to chat on Friday!!

**Comment by sghoweri** [comment]
Merging this down to master — cutting the next beta shortly!

**Pull request merged**
