### PR TITLE
PatternEngines: support multiple template engines

### PR DESCRIPTION
**Pull request by geoffp**
EDIT: newer PR pointed at feature branch is here:
https://github.com/pattern-lab/patternlab-node/pull/191

NOT READY FOR MERGE YET, this PR is only for review.

@bmuenzenmeyer, I've made some progress on a PatternEngine architecture. It's not remotely done or cleaned up yet, so please excuse any whitespace fussing, but I was hoping you'd look at it to see where I'm going with it and give me feedback. My approach is to incrementally move mustache-specific functionality into a new mustache PatternEngine as it becomes available. It's currently passing all unit tests (EDIT: no it's not, I just found `npm test`; it does pass `grunt nodeunit`), though lots more direct uses of mustache still need to be moved into the PatternEngine.

It's also a goal to be able to support (and unit test) whatever PatternEngines are implemented, but only activate them if their backing engines are installed by the end user as npm deps. So, if you `npm install handlebars`, the Handlebars PatternEngine and its unit tests should wake up and start doing things.

### CODE REVIEW

**Comment by geoffp** [comment]
I think I see what's broken; I'll fix it hopefully tomorrow.

**Comment by bmuenzenmeyer** [comment]
wow @geoffp this is a great contribution and time investment - THANK YOU!  :astonished: 

I will need to take some time to read through all this - hopefully this weekend. appreciate the work and the in process sharing. I wonder if it would help to push this to a feature branch rather than dev for now ?

**Comment by geoffp** [comment]
Yeah, I think a feature branch would be good. I'm sorry for the large code drop, I know it'll be hard to review. That's why I wanted to get this work in front of your eyes sooner rather than later.

**Comment by bmuenzenmeyer** [comment]
Hi @geoffp I just finished the work I had wanted to wrap up with Style Modifiers. Can you see if you can pull those changes and then point this PR to a feature branch?  In the meantime I will start reviewing.

Thanks

**Comment by geoffp** [comment]
Excellent! Sure thing. I'll merge the latest as soon as I can and then see if I can pass the unit tests as well.

Do you need to create the feature branch in this repository, or can I?

**Comment by bmuenzenmeyer** [comment]
Dunno if you can. I created https://github.com/pattern-lab/patternlab-node/tree/engines for you to hit

**Comment by bmuenzenmeyer** [comment]
@geoffp ping. just making sure you saw the above.

**Comment by geoffp** [comment]
Yes, I did. I'm trying to get the time to do this ASAP. Stay tuned! 😀

**Comment by bmuenzenmeyer** [comment]
No rush. Believe me, I understand how time flies :clock1030:

**Pull request closed without merging**
