### PR TITLE
chore: update @basalt/twig-renderer to version 2

### LINKED ISSUE #1259: Update engine-twig-php to latest @basalt/twig-renderer
I am using Pattern Lab Node `v5.13.1` on `Mac`, with Node `v12.18.0` `Custom` Edition.

##### Expected Behavior
* Twig Env uses 2 or better.

##### Actual Behavior
* Twig Env is 1.4.2 (basalt twig renderer needs update in package)

##### Steps to Reproduce
* Install latest `@pattern-lab/engine-twig-php`
* View Twig env version

### PR DESCRIPTION
**Pull request by patrickcate**
Closes #1259

updates @basalt/twig-renderer to version 2

### CODE REVIEW

**Comment by JosefBredereck** [comment]
It is that simple? 😨
That would be awesome.

**Comment by JosefBredereck** [comment]
Is that update downward compatible?

**Comment by patrickcate** [comment]
> Is that update downward compatible?

It technically [represents a break change](https://github.com/knapsack-cloud/twig-renderer/releases/tag/v2.0.0).

How are breaking changes in a single package handled in a monorepo?

**Comment by JosefBredereck** [comment]
> How are breaking changes in a single package handled in a monorepo?

I'm not sure how this would be handled.

I only needed this information for future releases to inform all users via a release note.

**Review by JosefBredereck — APPROVED** [review]

**Pull request merged**
