### PR TITLE
Show "CSS" and "JS" tabs in code section

### PR DESCRIPTION
**Pull request by malyw**
Pull request for https://github.com/pattern-lab/patternlab-node/issues/113

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Hi @malyw I will check this out this weekend. Excited at the prospect. Can you share some examples of how you are using this? Especially the JS

**Comment by malyw** [comment]
@bmuenzenmeyer Examples of usage:

**CSS**

Might be very useful for showing how to use e.g. mixins.
As example provided usage of Compass "ellipsis" mixin:
http://codepen.io/malyw/pen/doyrjr?editors=110

**JS**

Could be used e.g. for showing how to connect plugins.
As example- usage of jQuery UI Datepicker: http://codepen.io/malyw/pen/PqoLrN?editors=101

Given examples show just usage of 3rd party components, but if its part of your CSS/JS framework- this ability is exactly what user might looking for.

**Comment by malyw** [comment]
Hey @bmuenzenmeyer 
I also merged changes from "patternlab-node" **0.9.0 release** to the pull request.

**Comment by bmuenzenmeyer** [comment]
Hey @malyw thanks for that! I promised to check this out this weekend, but didn't get to it. Coincidentally, a coworker and I were talking about this and are excited to get it in.

**Comment by coreymcollins** [comment]
I was actually hoping to achieve this exact thing when I stumbled across this thread.  Wondering if there was any potential progress on merging this in?  Would love to be able to add JS and CSS to our code tabs!

**Comment by bmuenzenmeyer** [comment]
When talking to the Target folks, there was express interest in resurrecting this. I'd like us to figure out how it jives with https://github.com/pattern-lab/styleguidekit-assets-default

**Comment by malyw** [comment]
Closed in preference of the updated version for patternlab 1.3.0- https://github.com/pattern-lab/patternlab-node/pull/330

**Pull request closed without merging**
