### PR TITLE
Fix hidden pattern references

### PR DESCRIPTION
**Pull request by geoffp**
Addresses #469 

Summary of changes:
This is frustratingly simple for how much time it took. Two main changes to the non-test code:
1. Make the pattern prefix matching regex aware of leading underscores in pattern file names.
1. Factor it out and write it only once.
1. Also, pre-calculate the verbose partial name in the Pattern object. I thought I could use it, but I couldn't (handlebars doesn't tolerate slashes in partial syntax)

And lots of unit tests to prove it. I created a place for shared code in the tests.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
fixed a merge conflict - going to test this manually too next free time i get - kids up now - dad time

**Comment by geoffp** [comment]
Groovy. Do that dad time!

**Comment by geoffp** [comment]
And, thanks for doing the merge. I picked exactly the wrong time to do stuff to unit tests.

**Comment by bmuenzenmeyer** [comment]
@geoffp does using lineage to go to the hidden pattern work for you?

image

It does not for me using this quick test above

**Comment by bmuenzenmeyer** [comment]
I'm okay making this a separate issue too if need be. Just curious what is happening on your end.

**Comment by geoffp** [comment]
@bmuenzenmeyer Just tested -- no, it's not working for me. Separate ticket?

**Pull request merged**
