### PR TITLE
UIKit Code Panel + View All / Clean Public Fixes!

### PR DESCRIPTION
**Pull request by sghoweri**
# Summary
- Fixes several long running bugs relating to Code Panels, including View All page panels being completely broken after the first initial build of Pattern Lab, only being able to open one panel at a time while on View All pages (when they _do_ work), and panels only being able to be opened / closed once before breaking...
- Also fixes a semi-related issue I encountered regarding the broken `cleanPublic` config option... turns out that without the `cleanPublic` option enabled, the code panels also don't appear to get the data needed in order to work properly!
- This PR also tries to patch up some Navigation / Viewport bugs I've observed where loading up certain pages for the first time (via query string parameter) don't (always?) end up loading up in the iframe as expected
    - Note: I haven't 100% confirmed this however this could actually be related to the cleanPublic option not working as expected...
- Finally this PR also does some minor CSS cleanup with the code panel so the copy button doesn't start to overflow off the screen + the code panel height on View All pages (when expanded) is the height of the content itself (at least on larger screen sizes)

## Bugs Fixed
- https://github.com/pattern-lab/patternlab-node/issues/1057
- https://github.com/pattern-lab/patternlab-node/issues/1029
- https://github.com/pattern-lab/patternlab-node/issues/1024
- https://github.com/pattern-lab/patternlab-node/issues/988

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@sghoweri curious if you are also seeing this ? (when loading "all" or clicking on the logo)

image

**Comment by sghoweri** [comment]
Hmmm 🤔 

@bmuenzenmeyer let me dig a bit more into this one — I might try to split this up into two PRs (plus see if I can sprinkle a little Jest

**Comment by sghoweri** [comment]
Hmmm 🤔 

@bmuenzenmeyer let me dig a bit more into this one — I might try to split this up into two PRs (plus see if I can sprinkle a little Jest help as well to start chipping away at UIKit testing coverage...)

Hang tight!

**Comment by bmuenzenmeyer** [comment]
FYI, I had to make a minor uikit change here as part of a plugin fix.
https://github.com/pattern-lab/patternlab-node/pull/1077/files#diff-963382f8b9962328c07d8308327620c7

Not sure if related


(I probably should start having you review instead of late night merging)

**Comment by bmuenzenmeyer** [comment]
the hosted preview now also shows the same behavior i was seeing locally

**Comment by bmuenzenmeyer** [comment]
superceded by #1094 

@sghoweri if I am misunderstanding - please reopen

**Comment by sghoweri** [comment]
> superceded by #1094
> 
> @sghoweri if I am misunderstanding - please reopen

Nope, all good. #1094 supersedes this one 👍🏼

**Pull request closed without merging**
