### PR TITLE
Added styleGuideExcludes setting

### PR DESCRIPTION
**Pull request by bramsmulders**
I've added the styleGuideExcludes option in the config.
Here you can exclude templates from the styleguide(all view).

Fixes: #158

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@bramsmulders you are an open source hero! Thanks so much for this work, and the poke. Looks pretty simple to merge in. I am almost done with https://github.com/pattern-lab/patternlab-node/issues/95 which is occupying most of my time, after which this will get my full attention. In the meantime, if you like, you could add a unit test. I am trying to cover more and more of patternlab node. If you don't I will do so.

Again, thanks again for knocking something out! Remind me if I don't get to this in a week or so. :hourglass_flowing_sand:

**Comment by bmuenzenmeyer** [comment]
Hi @bramsmulders I just finished #95 which likely broke the auto-merge of this feature. It's small enough to resolve on my side using command line, which I'll do tomorrow or the next day or the next. Not enough energy to do so tonight. 

Cheers

**Comment by bramsmulders** [comment]
Hey @bmuenzenmeyer! Sorry for my late response, i was very busy pas couple of days. It is nice to see my pull request merged. I do not know anything about configuring unit tests, i'll poke around in the current unit tests you have here. Lets see if i can come up with something. 

In the mean time this new styleguideExcludes setting also needs some documenting. I'll try to create a pull request for that this week.

**Comment by bmuenzenmeyer** [comment]
I agree this should be documented. I am getting a bit hesitant to keep jamming things in the `README` as very soon there will be a home for node documentation on [patternlab.io](https://github.com/pattern-lab/website/tree/dev).  Either way, you create something and I'm sure it will get sorted out.

**Pull request merged**
