### PR TITLE
Css syntax corrected

### PR DESCRIPTION
**Pull request by afonsopacifer**
Correct branch :)

### CODE REVIEW

**Comment by afonsopacifer** [comment]
Sorry! Now I sent the wrong branch :/

**Comment by bmuenzenmeyer** [comment]
this looked right?

**Comment by afonsopacifer** [comment]
@bmuenzenmeyer, Sorry again, I need to sleep :)

**Comment by bmuenzenmeyer** [comment]
Hi @afonsopacifer 

Something at the back of my mind was itching about this PR.

This particular watch line is meant to pick up the `.scss` files located here:

* `./public/styleguide/css/styleguide-specific.scss`
* `./public/styleguide/css/styleguide.scss`
* `./public/styleguide/css/static.scss`

It's a tad confusing that there are source files inside the public directory - but this structure mirrors how patternlab - php used to be oriented, before a major file restructure on that project's part.   So for now, to accommodate users that wish to change these files with the sass watcher, the line should remain as is.

**Comment by afonsopacifer** [comment]
Ok  :)

**Pull request closed without merging**
