### PR TITLE
Change backslashes in Pattern subdir property to forward slashes

### PR DESCRIPTION
**Pull request by sandrojohanides**
Addresses #559

Summary of changes:
Change backslashes in Pattern subdir property to forward slashes

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
I ran tests against this just now and received 45 errors. need to look into it further at some point

**Comment by somatonic** [comment]
I manually added this fix to my installation PL 2.7.2 and it doesn't work, It breaks the patternlab navigation on top ...

**Comment by sandrojohanides** [comment]
Yes, that was not a good idea at all.

**Comment by greenthoms** [comment]
Any work-arounds for this issue?

**Comment by bmuenzenmeyer** [comment]
closing this due to inactivity

**Pull request closed without merging**
