### PR TITLE
ci(package.json): changed node version to version >=8

### PR DESCRIPTION
**Pull request by benhalverson**
#870 

Summary of changes: 
- Updated package.json to >=8 
- Added .nvmrc file

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
@benhalverson thanks for this - it's a good start. Would you like to take on the additional work outlined in 
 #870 ? If not, I can finish it up.

- [ ] package.json engines
- [ ] documentation / README / shields (top-level, core)

**Comment by benhalverson** [comment]
@bmuenzenmeyer yep should I update all the package.json files for each package? 
I can also update the readme. I assume it should say something like we have updated to work with the latest LTS version of node.

**Comment by benhalverson** [comment]
I think thats a better idea 👍

**Comment by benhalverson** [comment]
@bmuenzenmeyer can you point me to which files are not on node 10 yet?

**Comment by bmuenzenmeyer** [comment]
@benhalverson 

I think I overstated how many instances you'd missed. I apologize for holding up this essential work.

- [ ] https://github.com/pattern-lab/patternlab-node/blob/dev/.github/CONTRIBUTING.md (probably should change to just mention the `.nvmrc` files
- [ ] packages/cli/.nvmrc in the PR itself

**Comment by bmuenzenmeyer** [comment]
Pushed those two additional entries to `dev`

**Comment by bmuenzenmeyer** [comment]
@benhalverson thank you for taking on this work!!!! 

❤️

**Pull request merged**
