### PR TITLE
Fixed the path to the plugins object. Issue 91 on the edition-node-gulp repo

### PR DESCRIPTION
**Pull request by giuseppepaul**
Minor change to fix this issue: https://github.com/pattern-lab/edition-node-gulp/issues/91
Updated the path to the plugins object.

### CODE REVIEW

**Comment by giuseppepaul** [comment]
I've updated it and it works fine :) 

`output += 'var plugins = ' + JSON.stringify(patternlab.plugins || []) + ';' + eol;`

...but before I push it, I was thinking maybe an if statement inside the buildFrontend function before exportData gets called might be cleaner?

`if (patternlab.plugins === undefined) patternlabs.plugins = [];`

What do you think?

**Comment by bmuenzenmeyer** [comment]
I am okay with either solution - but prefer mine more because it's closer to the eventual output

**Comment by giuseppepaul** [comment]
No probs, I've updated :) cheers

**Comment by bmuenzenmeyer** [comment]
Thanks for the help @giuseppepaul

**Pull request merged**
